export const USER_IS_NOT_AUTHENTICATED = 'USER_IS_NOT_AUTHENTICATED';
export const USER_IS_AUTHENTICATED = 'USER_IS_AUTHENTICATED';
export const USER_ACCESS_DENIED = 'USER_ACCESS_DENIED';
export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const USER_UPDATE_TOKEN = 'USER_UPDATE_TOKEN';
export const USER_UPDATE_= 'USER_UPDATE_TOKEN';
export const USER_REQUEST_FAILED = 'USER_REQUEST_FAILED';
export const USER_REQUEST_SUCCESS = 'USER_REQUEST_SUCCESS';

export const MENU_SIDEBAR_TOGGLE = 'MENU_SIDEBAR_TOGGLE';
export const MENU_SIDEBAR_IS_EXPANDED = 'MENU_SIDEBAR_IS_EXPANDED';
export const MENU_SIDEBAR_IS_COLLAPSED = 'MENU_SIDEBAR_IS_COLLAPSED';

export const CALENDAR_GET_EVENTS = 'CALENDAR_GET_EVENTS';
export const CALENDAR_GET_DOCTORS = 'CALENDAR_GET_DOCTORS';
export const CALENDAR_GET_CATEGORIES = 'CALENDAR_GET_CATEGORIES';

// Modules

export const MODULE_LOADING = 'MODULE_LOADING';
export const MODULE_INIT_REQUEST = 'MODULE_INIT_REQUEST';
export const MODULE_INIT_FAILED = 'MODULE_INIT_FAILED';
export const MODULE_INIT_SUCCESS = 'MODULE_INIT_SUCCESS';

export const SCHEDULE_INIT = 'SCHEDULE_INIT';
export const SCHEDULE_GET_PENDING_EVENTS = 'SCHEDULE_GET_PENDING_EVENTS';
export const SCHEDULE_EXAMPLE = 'SCHEDULE_EXAMPLE'; // for example only

// New kind of methods. Require only one type per action.
export const NOTIFICATION_GET_SC_TASKS = 'NOTIFICATION_GET_SC_TASKS';
export const NOTIFICATION_GET_SC_EVENTS_STATUS = 'NOTIFICATION_GET_SC_EVENTS_STATUS';
export const NOTIFICATION_TEST = 'NOTIFICATION_TEST';